source 'https://github.com/Humein/BX_Podspec_Repo.git'   # 私有库
source 'https://github.com/CocoaPods/Specs.git'  # 官方库

#use_frameworks!
use_modular_headers!
inhibit_all_warnings!

platform :ios, '8.0'

target 'TiKuBaseModulesRepo_Example' do
  pod 'TiKuBaseModulesRepo', :path => '../'

  target 'TiKuBaseModulesRepo_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
    pod 'SDWebImage'
    pod 'BaseClassModulesRepo', '~> 0.1.6'
  end
  
  
  post_install do |installer|
    #设置build setting
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
           config.build_settings['SWIFT_VERSION'] = '5.0'
           config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
           config.build_settings['DEFINES_MODULE'] = 'YES'
          end
         end
  end
end
